steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/nlife-ai-unit-test/back-python-image:$COMMIT_SHA', '.']
  dir: 'back'
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/nlife-ai-unit-test/back-python-image:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'back-python-image'
  - '--image'
  - 'gcr.io/nlife-ai-unit-test/back-python-image:$COMMIT_SHA'
  - '--region'
  - 'asia-northeast1'
images:
- 'gcr.io/nlife-ai-unit-test/back-python-image:$COMMIT_SHA'
options:
  logging: 'CLOUD_LOGGING_ONLY'
